/**
 * İş Türleri — Feature Flag + Terminoloji + İçerik Haritası
 * Her sektör için hangi modüllerin görüneceğini, UI terimlerini ve varsayılan metinleri tanımlar.
 */

export const BUSINESS_TYPES = {
  // ─── FOTOĞRAFÇILIK ────────────────────────────
  photographer: {
    name: "Fotoğrafçı",
    icon: "📸",
    desc: "Düğün, dış çekim, etkinlik fotoğrafçılığı",
    heroTitle: "Anılarınızı\nSanata Dönüştürüyoruz",
    heroSub: "Profesyonel fotoğraf çekimi ile özel anlarınızı ölümsüzleştiriyoruz.",
    defaultSlogan: "Anılarınızı sanata dönüştürüyoruz.",
    features: {
      photoSelection: true,
      albumModels: true,
      workflow: true,
      galleryDelivery: true,
      onlineLink: false,
      contract: true,
      portfolio: true,
      categories: true,
      discountMonths: true,
      events: true,
    },
    terms: {
      client: "Müşteri",
      clients: "Müşteriler",
      appointment: "Rezervasyon",
      appointments: "Rezervasyonlar",
      service: "Paket",
      services: "Paketler",
      provider: "Fotoğrafçı",
      session: "Çekim",
      sessions: "Çekimler",
      upcoming: "Yaklaşan Çekimler",
      brandSuffix: "studio",
      placeName: "Stüdyo",
      packageNamePlaceholder: "Elit Düğün Hikayesi",
      packageFeaturesPlaceholder: "200 fotoğraf, albüm, drone",
    },
    homeSections: ["hero", "portfolio", "packages", "events", "testimonials", "contact"],
  },

  // ─── DOKTOR ───────────────────────────────────
  doctor: {
    name: "Doktor",
    icon: "🩺",
    desc: "Klinik, muayenehane, sağlık merkezi",
    heroTitle: "Sağlığınız\nGüvenli Ellerde",
    heroSub: "Uzman kadromuzla sağlığınız için en doğru çözümleri sunuyoruz.",
    defaultSlogan: "Sağlığınız güvenli ellerde.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: false,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Hasta",
      clients: "Hastalar",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Muayene",
      services: "Muayeneler",
      provider: "Doktor",
      session: "Muayene",
      sessions: "Muayeneler",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "Klinik",
      packageNamePlaceholder: "Genel Muayene",
      packageFeaturesPlaceholder: "Tansiyon ölçümü, reçete, kontrol",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── DİŞ HEKİMİ ──────────────────────────────
  dentist: {
    name: "Diş Hekimi",
    icon: "🦷",
    desc: "Diş kliniği, ağız ve diş sağlığı merkezi",
    heroTitle: "Gülüşünüze\nDeğer Katıyoruz",
    heroSub: "Modern diş tedavisi ile sağlıklı ve estetik gülüşler sunuyoruz.",
    defaultSlogan: "Gülüşünüze değer katıyoruz.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: false,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Hasta",
      clients: "Hastalar",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Tedavi",
      services: "Tedaviler",
      provider: "Diş Hekimi",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "Klinik",
      packageNamePlaceholder: "Diş Beyazlatma",
      packageFeaturesPlaceholder: "Muayene, röntgen, uygulama",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── PSİKOLOG ─────────────────────────────────
  psychologist: {
    name: "Psikolog / Terapist",
    icon: "🧠",
    desc: "Bireysel terapi, çift terapisi, danışmanlık",
    heroTitle: "İç Huzurunuza\nGiden Yol",
    heroSub: "Profesyonel terapi desteğiyle kendinizi daha iyi tanıyın ve güçlenin.",
    defaultSlogan: "İç huzurunuza giden yol.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: true,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Danışan",
      clients: "Danışanlar",
      appointment: "Seans",
      appointments: "Seanslar",
      service: "Terapi",
      services: "Terapi Programları",
      provider: "Terapist",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Seanslar",
      brandSuffix: "panel",
      placeName: "Ofis",
      packageNamePlaceholder: "Bireysel Terapi",
      packageFeaturesPlaceholder: "50 dk seans, online destek",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── DİYETİSYEN ───────────────────────────────
  dietitian: {
    name: "Diyetisyen",
    icon: "🥗",
    desc: "Beslenme danışmanlığı, diyet programları",
    heroTitle: "Sağlıklı Yaşam\nDoğru Beslenmeyle Başlar",
    heroSub: "Kişiye özel beslenme programlarıyla hedeflerinize ulaşmanızı sağlıyoruz.",
    defaultSlogan: "Sağlıklı yaşam doğru beslenmeyle başlar.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Danışan",
      clients: "Danışanlar",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Konsültasyon",
      services: "Konsültasyonlar",
      provider: "Diyetisyen",
      session: "Görüşme",
      sessions: "Görüşmeler",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "Ofis",
      packageNamePlaceholder: "Kişisel Beslenme Programı",
      packageFeaturesPlaceholder: "Diyet planı, haftalık takip, ölçüm",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── SPOR HOCASI / PT ────────────────────────
  coach: {
    name: "Spor Hocası / PT",
    icon: "🏋️",
    desc: "Kişisel antrenör, fitness, yoga, pilates",
    heroTitle: "Hedefinize\nBirlikte Ulaşalım",
    heroSub: "Kişiye özel antrenman programlarıyla en iyi versiyonunuza ulaşın.",
    defaultSlogan: "Hedefinize birlikte ulaşalım.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Üye",
      clients: "Üyeler",
      appointment: "Antrenman",
      appointments: "Antrenmanlar",
      service: "Program",
      services: "Programlar",
      provider: "Antrenör",
      session: "Antrenman",
      sessions: "Antrenmanlar",
      upcoming: "Yaklaşan Antrenmanlar",
      brandSuffix: "panel",
      placeName: "Salon",
      packageNamePlaceholder: "Kişisel Antrenman",
      packageFeaturesPlaceholder: "1 saat PT, program, takip",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── GÜZELLİK / KUAFÖR ──────────────────────
  beauty: {
    name: "Güzellik / Kuaför",
    icon: "💇",
    desc: "Kuaför, güzellik merkezi, cilt bakımı, spa",
    heroTitle: "Güzelliğinize\nDokunuyoruz",
    heroSub: "Profesyonel bakım ve güzellik hizmetleriyle kendinizi özel hissedin.",
    defaultSlogan: "Güzelliğinize dokunuyoruz.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: false,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Müşteri",
      clients: "Müşteriler",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Hizmet",
      services: "Hizmetler",
      provider: "Uzman",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "Salon",
      packageNamePlaceholder: "Saç Bakımı Paketi",
      packageFeaturesPlaceholder: "Yıkama, kesim, fön, bakım",
    },
    homeSections: ["hero", "services", "portfolio", "contact"],
  },

  // ─── VETERİNER ────────────────────────────────
  veterinarian: {
    name: "Veteriner",
    icon: "🐾",
    desc: "Veteriner kliniği, hayvan hastanesi",
    heroTitle: "Dostlarınız\nGüvende",
    heroSub: "Sevimli dostlarınızın sağlığı için profesyonel veteriner hizmeti sunuyoruz.",
    defaultSlogan: "Dostlarınız güvende.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: false,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Hasta Sahibi",
      clients: "Hasta Sahipleri",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Muayene",
      services: "Muayeneler",
      provider: "Veteriner",
      session: "Muayene",
      sessions: "Muayeneler",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "Klinik",
      packageNamePlaceholder: "Genel Muayene",
      packageFeaturesPlaceholder: "Muayene, aşı, kontrol",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── FİZYOTERAPİST ───────────────────────────
  physiotherapist: {
    name: "Fizyoterapist",
    icon: "🦴",
    desc: "Fizik tedavi, rehabilitasyon, manuel terapi",
    heroTitle: "Hareket Özgürlüğünüz\nBizimle Başlar",
    heroSub: "Fizik tedavi ve rehabilitasyon ile sağlıklı hareket kabiliyetinizi geri kazanın.",
    defaultSlogan: "Hareket özgürlüğünüz bizimle başlar.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: false,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
    },
    terms: {
      client: "Hasta",
      clients: "Hastalar",
      appointment: "Seans",
      appointments: "Seanslar",
      service: "Tedavi",
      services: "Tedaviler",
      provider: "Fizyoterapist",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Seanslar",
      brandSuffix: "panel",
      placeName: "Klinik",
      packageNamePlaceholder: "Manuel Terapi Seansı",
      packageFeaturesPlaceholder: "Manuel terapi, egzersiz programı",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── ÖZEL ÖĞRETMEN / EĞİTMEN ────────────────
  tutor: {
    name: "Özel Öğretmen / Eğitmen",
    icon: "📚",
    desc: "Özel ders, dil kursu, müzik dersi, eğitim",
    heroTitle: "Başarıya\nBirlikte Ulaşalım",
    heroSub: "Birebir eğitim desteğiyle akademik hedeflerinize ulaşmanızı sağlıyoruz.",
    defaultSlogan: "Başarıya birlikte ulaşalım.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Öğrenci",
      clients: "Öğrenciler",
      appointment: "Ders",
      appointments: "Dersler",
      service: "Kurs",
      services: "Kurslar",
      provider: "Eğitmen",
      session: "Ders",
      sessions: "Dersler",
      upcoming: "Yaklaşan Dersler",
      brandSuffix: "panel",
      placeName: "Ofis",
      packageNamePlaceholder: "Matematik Özel Ders",
      packageFeaturesPlaceholder: "60 dk ders, ödev takibi, konu anlatım",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── AVUKAT ───────────────────────────────────
  lawyer: {
    name: "Avukat",
    icon: "⚖️",
    desc: "Hukuk bürosu, arabuluculuk, danışmanlık",
    heroTitle: "Hukukta\nGüvenilir Çözüm Ortağınız",
    heroSub: "Deneyimli kadromuzla hukuki süreçlerinizde yanınızdayız.",
    defaultSlogan: "Hukukta güvenilir çözüm ortağınız.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: true,
      portfolio: true,
      categories: false,
      discountMonths: false,
      events: true,
    },
    terms: {
      client: "Müvekkil",
      clients: "Müvekkiller",
      appointment: "Görüşme",
      appointments: "Görüşmeler",
      service: "Danışmanlık",
      services: "Danışmanlık Hizmetleri",
      provider: "Avukat",
      session: "Görüşme",
      sessions: "Görüşmeler",
      upcoming: "Yaklaşan Görüşmeler",
      brandSuffix: "hukuk",
      placeName: "Ofis",
      packageNamePlaceholder: "İlk Görüşme",
      packageFeaturesPlaceholder: "30 dk görüşme, dosya inceleme",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },

  // ─── DANIŞMAN / KOÇ ──────────────────────────
  consultant: {
    name: "Danışman / Koç",
    icon: "💼",
    desc: "İş danışmanlığı, kariyer koçluğu, yaşam koçu",
    heroTitle: "Potansiyelinizi\nBirlikte Keşfedelim",
    heroSub: "Profesyonel koçluk ve danışmanlık hizmetleriyle hedeflerinize ulaşın.",
    defaultSlogan: "Potansiyelinizi birlikte keşfedelim.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: true,
      portfolio: true,
      categories: false,
      discountMonths: false,
    },
    terms: {
      client: "Danışan",
      clients: "Danışanlar",
      appointment: "Seans",
      appointments: "Seanslar",
      service: "Danışmanlık",
      services: "Danışmanlık Paketleri",
      provider: "Danışman",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Seanslar",
      brandSuffix: "panel",
      placeName: "Ofis",
      packageNamePlaceholder: "Birebir Koçluk Seansı",
      packageFeaturesPlaceholder: "50 dk seans, aksiyon planı",
    },
    homeSections: ["hero", "services", "about", "contact"],
  },

  // ─── DİĞER ───────────────────────────────────
  other: {
    name: "Diğer",
    icon: "🏢",
    desc: "Randevu ile çalışan diğer sektörler",
    heroTitle: "Profesyonel\nHizmet Anlayışı",
    heroSub: "Alanında uzman kadromuzla kaliteli hizmet sunuyoruz.",
    defaultSlogan: "Profesyonel hizmet anlayışı.",
    features: {
      photoSelection: false,
      albumModels: false,
      workflow: false,
      galleryDelivery: false,
      onlineLink: true,
      contract: false,
      portfolio: true,
      categories: false,
      discountMonths: false,
    },
    terms: {
      client: "Müşteri",
      clients: "Müşteriler",
      appointment: "Randevu",
      appointments: "Randevular",
      service: "Hizmet",
      services: "Hizmetler",
      provider: "Uzman",
      session: "Seans",
      sessions: "Seanslar",
      upcoming: "Yaklaşan Randevular",
      brandSuffix: "panel",
      placeName: "İşletme",
      packageNamePlaceholder: "Standart Hizmet",
      packageFeaturesPlaceholder: "Danışmanlık, takip, destek",
    },
    homeSections: ["hero", "services", "events", "about", "contact"],
  },
};

/**
 * Sektör bilgisini getir (fallback: photographer)
 */
export function getBusinessType(id) {
  return BUSINESS_TYPES[id] || BUSINESS_TYPES.photographer;
}

/**
 * Sektör listesini array olarak döndür (onboarding seçici için)
 */
export function getBusinessTypeList() {
  return Object.entries(BUSINESS_TYPES).map(([id, bt]) => ({
    id,
    ...bt,
  }));
}
